name = "Glorppack"
author = "Starr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0afffe5fc2d846b0ba0c488cfbe0c69055c4c0405eff6e9f04c2046f9c60f9f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
