name = "Glorppack"
author = "Starr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baf504756bf46348264482ee11475dafcba15942af8405757cbb86ecdb3d44c4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
