name = "Glorppack"
author = "Starr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e065950204d5f3837aa887176d95c263778c8083ca2cf622ba1303248cc37d9a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
