#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 28 18:59:54 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
